spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebborize_test?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 299792458

mybatis:
  type-aliases-package: org.airflare.ebborize.pojo
  configuration:
    map-underscore-to-camel-case: true