spring:
  datasource:
    url: jdbc:mysql://39.105.113.11:3306/ebborize?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Heguanqiao1!

mybatis:
  type-aliases-package: org.airflare.ebborize.pojo
  configuration:
    map-underscore-to-camel-case: true